[package]
name = "clock"
version = "0.1.0"
authors = ["Kenneth Uildriks <Ken.Uildriks@coxautoinc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7"
chrono = "0.4"